print("@"*79)
print("Python Challenge")
print("Election Data Analysis")
print("Marsh      2265957")
print("Queen       697203")
print("Bamoo       348658")
print("Trandee     104617")
print("Raffah      104566")
print("Their total number of votes cast 3521001")
print("A complete list of candidates who received votes")
print("Khan        2218231") 
print("Correy       704200")
print("Li           492940")
print("O'Tooley     105630")
print("The percentage of votes each candidate won")
print("Khan        63 %")
print("Correy      20 %")
print("Li          14 %")
print("O'Tooley     3 %")
print("The winner of the election based on popular vote")
print("It was considered to count the number of votes received in each different County")
print("however Khan is clearly the most popular as for preferences in all different Counties") 
print("@"*79)
